using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Notification.Infrastructure.Migrations.Global
{
    /// <inheritdoc />
    public partial class AddAuditLog : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""AuditLogs"" (
                    ""Id"" bigint GENERATED BY DEFAULT AS IDENTITY,
                    ""Action"" text NOT NULL,
                    ""EntityType"" text NOT NULL,
                    ""EntityId"" text,
                    ""TenantId"" text,
                    ""UserId"" text,
                    ""UserEmail"" text,
                    ""Before"" text,
                    ""After"" text,
                    ""IpAddress"" text,
                    ""OccurredAt"" timestamp with time zone NOT NULL,
                    CONSTRAINT ""PK_AuditLogs"" PRIMARY KEY (""Id"")
                );
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "AuditLogs");
        }
    }
}
