"""sqlalchemy_2_typed_models_update

Revision ID: 0ac3b2ff2846
Revises: 
Create Date: 2026-04-10 19:33:16.706845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import models
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '0ac3b2ff2846'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('AiChatMessage', 'PromptTokens',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('AiChatMessage', 'CompletionTokens',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('AiChatMessage', 'CreatedAt',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.alter_column('AiChatSession', 'CreatedAt',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.alter_column('AiTokenUsageLog', 'CreatedAt',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('AiTokenUsageLog', 'CreatedAt',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('AiChatSession', 'CreatedAt',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('AiChatMessage', 'CreatedAt',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('AiChatMessage', 'CompletionTokens',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('AiChatMessage', 'PromptTokens',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
