"""Add description column to AiProviderSettings

Revision ID: bd0e13c312b3
Revises: e9f3a1c2d5b7
Create Date: 2026-04-28 10:44:58.774373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import models



# revision identifiers, used by Alembic.
revision: str = 'bd0e13c312b3'
down_revision: Union[str, None] = 'e9f3a1c2d5b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('AiProviderSettings', sa.Column('Description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('AiProviderSettings', 'Description')
    # ### end Alembic commands ###
