"""Change_UserId_to_Integer

Revision ID: d27084ec4fea
Revises: b1c4e8d9f2a3
Create Date: 2026-04-26 00:04:28.780030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import models



# revision identifiers, used by Alembic.
revision: str = 'd27084ec4fea'
down_revision: Union[str, None] = 'b1c4e8d9f2a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE "AiChatSession" ALTER COLUMN "UserId" TYPE INTEGER USING 0')
    op.execute('ALTER TABLE "AiTokenUsageLog" ALTER COLUMN "UserId" TYPE INTEGER USING 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('AiTokenUsageLog', 'UserId',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('AiChatSession', 'UserId',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False)
    # ### end Alembic commands ###
